# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases\archive.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.login_test import TestCaseLogin as Login


class TestCaseArchive(HttpRunner):

    config = Config("档案管理").base_url("http://jspro-gateway-test.gcnao.cn").verify(False)

    teststeps = [
        Step(RunTestCase("获取token").call(Login).export(*["token"])),
        Step(
            RunRequest("档案管理-统计分析-项目收集统计")
            .get("/archives-service/statisticalAnalysis/getCollectStatisticalData")
            .with_params(
                **{
                    "projectId": "bfc32d4547fb4e3bbd945a25dd1d64fe",
                    "pageIndex": 1,
                    "pageSize": 10,
                    "collectType": "project",
                }
            )
            .with_headers(**{"Authorization": "$token"})
            .validate()
            .assert_equal("body.code", "200")
            .assert_equal("body.message", "ok")
        ),
        Step(
            RunRequest("档案管理-统计分析-合同段收集统计")
            .get("/archives-service/statisticalAnalysis/getCollectStatisticalData")
            .with_params(
                **{
                    "projectId": "bfc32d4547fb4e3bbd945a25dd1d64fe",
                    "pageIndex": 1,
                    "pageSize": 10,
                    "collectType": "contract",
                }
            )
            .with_headers(**{"Authorization": "$token"})
            .validate()
            .assert_equal("body.code", "200")
            .assert_equal("body.message", "ok")
        ),
    ]


if __name__ == "__main__":
    TestCaseArchive().test_start()
