# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases\getCollectStatisticalData.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.dd_test_login_test import TestCaseDdTestLogin as DdTestLogin


class TestCaseGetcollectstatisticaldata(HttpRunner):

    config = (
        Config("archives-service-request")
        .base_url("http://jspro-gateway-test.gcnao.cn")
        .verify(False)
    )

    teststeps = [
        Step(RunTestCase("get token").call(DdTestLogin).export(*["token"])),
        Step(
            RunRequest("getCollectStatisticalData")
            .get("/archives-service/statisticalAnalysis/getCollectStatisticalData")
            .with_params(
                **{
                    "projectId": "bfc32d4547fb4e3bbd945a25dd1d64fe",
                    "pageIndex": 1,
                    "pageSize": 10,
                    "collectType": "project",
                }
            )
            .with_headers(**{"Authorization": "$token"})
            .validate()
            .assert_equal("body.code", "200")
            .assert_equal("body.message", "ok")
        ),
    ]


if __name__ == "__main__":
    TestCaseGetcollectstatisticaldata().test_start()
