# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases\login.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLogin(HttpRunner):

    config = (
        Config("登录")
        .base_url("http://dd-test.gcnao.cn")
        .verify(False)
        .export(*["token"])
    )

    teststeps = [
        Step(
            RunRequest("获取图片ID")
            .get("/gateway/account/captcha/image")
            .with_params(**{"md": "${get_time()}", "captchaType": "PERSON_LOGIN"})
            .extract()
            .with_jmespath("body.result.id", "captchaId")
            .validate()
            .assert_equal("body.message", "请求处理成功")
        ),
        Step(
            RunRequest("获取token")
            .with_variables(
                **{
                    "text": {
                        "username": "19812341111",
                        "password": "a123456",
                        "captcha": "1234",
                        "captchaId": "$captchaId",
                        "accountType": "PERSONAL",
                        "captchaType": "PERSON_LOGIN",
                    },
                    "encryptData": "${get_encrypt($text)}",
                }
            )
            .post("/gateway/account/loginV2")
            .with_data({"data": "$encryptData"})
            .extract()
            .with_jmespath("body.result", "token")
            .validate()
            .assert_equal("body.message", "请求处理成功")
        ),
    ]


if __name__ == "__main__":
    TestCaseLogin().test_start()
